### ISSUE TITLE
[v3] algosdk dependency

### ISSUE THREAD

**Issue by PhearZero** [TxnLab/use-wallet#192]
# Overview

Algosdk depedency is pinned to a specific version, when the dependency cannot be deduplicated it will cause errors with any Transactions. This is something that has come up before as well: algorand/js-algorand-sdk/issues/740

# Problem:

A transaction is trying to be created twice in the `instantiateTxnIfNeeded` call even though it is a valid instance of a Transaction. This is due to the `algosdk` being included twice in a project that depends on a different version than the currently pinned version.

```
Error: address seems to be malformed
    at decodeAddress (address.ts:49:11)
    at new Transaction (transaction.ts:264:24)
    at instantiateTxnIfNeeded (transaction.ts:1378:7)
    at Kmd.signTransaction (kmd.ts:264:20)
    at kmd.ts:236:38
    at Array.map (<anonymous>)
    at _a5.signTransactions (kmd.ts:236:18)
    at async _a5.transactionSigner (base.ts:67:28)
    at async Promise.all (:5173/index 0)
    at async _AtomicTransactionComposer.gatherSignatures (composer.ts:541:25)
```

# Solution

Easiest solution would be adding `algosdk` to the `peerDependencies` and allowing `^2.7.0`.

# Details:

- "@txnlab/use-wallet-react": "^3.0.0-rc.2",
- Vite React-TS
- KMD Provider

**Comment by drichar** [comment]
Ah, thank you. I wasn't aware of this issue. Making `algosdk` a required peer dependency does seem like the best solution. Probably better to have the library and consuming app always be in sync anyway.

Appreciate the PR! I'll merge it and update the documentation and example apps in the next release.
